name: xapptor_logic
description: Logic Module for util functions like cross-platform downloaders and functions to retrieve remote info.
# repository: https://github.com/Xapptor/xapptor_logic
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.3

environment:
  sdk: ">=3.1.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

  palette_generator: ^0.3.3+7
  http: ^1.6.0
  intl: ^0.19.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  geolocator: ^13.0.4
  geocoding: ^4.0.0
  universal_platform: ^1.1.0
  syncfusion_flutter_xlsio: ^28.2.6
  shared_preferences: ^2.5.3
  characters: ^1.3.0
  crypto: ^3.0.7
  device_info_plus: ^11.3.0
  web: ^1.1.1
  video_player: ^2.10.0

  # xapptor_router: ^0.0.2

  xapptor_db:
    path: ../xapptor_db
  xapptor_router:
    path: ../xapptor_router

dependency_overrides:
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
